apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patchesStrategicMerge:
- clusterrolebindings/cluster-readers.yaml
- configmaps/cluster-monitoring-config.yaml
- configmaps/user-workload-monitoring-config.yaml
- groups/cluster-admins.yaml
- groups/cluster-readers.yaml
- groups/grafana-admin.yaml
- groups/grafana-editor.yaml
- groups/grafana-viewer.yaml
- groups/inception-admins.yaml
- groups/kepler-admins.yaml
- groups/kubeflow-admin.yaml
- groups/odh-admin.yaml
- groups/odh-users.yaml
- groups/pachyderm-admins.yaml
- groups/seldon-admin.yaml
resources:
- ../../../base/core/configmaps/cluster-monitoring-config
- ../../../base/core/configmaps/user-workload-monitoring-config
- ../../../base/core/namespaces/acme-operator
- ../../../base/core/namespaces/aicoe-meteor
- ../../../base/core/namespaces/datahub-linkedin
- ../../../base/core/namespaces/dex
- ../../../base/core/namespaces/dex-secondary
- ../../../base/core/namespaces/inception
- ../../../base/core/namespaces/kafka
- ../../../base/core/namespaces/kubeflow
- ../../../base/core/namespaces/multinode-demo
- ../../../base/core/namespaces/odh-jupyterhub
- ../../../base/core/namespaces/odh-seldon
- ../../../base/core/namespaces/odh-superset
- ../../../base/core/namespaces/odh-trino
- ../../../base/core/namespaces/odh-trino-dev
- ../../../base/core/namespaces/openmetadata
- ../../../base/core/namespaces/opf-dashboard
- ../../../base/core/namespaces/opf-jupyterhub-stage
- ../../../base/core/namespaces/sandbox
- ../../../base/core/namespaces/sostrades-namespace
- ../../../base/user.openshift.io/groups/cluster-admins
- ../../../base/user.openshift.io/groups/cluster-readers
- ../../../base/rbac.authorization.k8s.io/clusterrolebindings/acme-operator
- ../../../base/rbac.authorization.k8s.io/clusterrolebindings/cluster-reader-k8s-annotations-exporter
- ../../../base/rbac.authorization.k8s.io/clusterrolebindings/cluster-readers
- ../../../base/rbac.authorization.k8s.io/clusterroles/acme-operator
- ../../../bundles/external-secrets-operator
- ../../../bundles/cert-manager
- ../../../bundles/grafana-operator
- ../../../bundles/kepler
- ../../../bundles/opf-monitoring
- ../../../bundles/opendatahub-operator-manual
- ../../../bundles/openshift-pipelines
- ../../../bundles/reloader
- ../../../bundles/training-operator
- ../common
- apiserver
- configmaps/service-catalog-k8s-plugin.yaml
- externalsecrets
- ingresscontroller
- machinesets
- nodefeaturediscovery
- machineconfigs/kepler
- nvidia-gpu
- secret-mgmt
