apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../base/apiextensions.k8s.io/customresourcedefinitions/prowjobs.prow.k8s.io
- ../../../base/core/namespaces/dex
- ../../../base/core/namespaces/osc-ci-prow
- ../../../base/core/namespaces/osc-ci-test-pods
- ../../../bundles/external-secrets-operator
- ../../../bundles/vault
- secret-mgmt

