apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: osc
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: vault-ui
    helm.sh/chart: vault-0.18.0
  name: osc-vault-ui
  namespace: vault
spec:
  ports:
    - name: http
      port: 8200
      targetPort: 8200
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/instance: osc
    app.kubernetes.io/name: vault
    component: server
  type: ClusterIP
