apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/config.openshift.io/projects/cluster
  - ../../../base/operator.openshift.io/consoles/cluster
  - ../../../base/rbac.authorization.k8s.io/clusterrolebindings/cluster-admins-rb
  - ../../../base/rbac.authorization.k8s.io/clusterrolebindings/self-provisioners
  - ../../../base/user.openshift.io/groups/aicos-osc-admins
  - ../../../base/user.openshift.io/groups/grafana-editor
  - ../../../base/user.openshift.io/groups/kepler-admins
  - ../../../base/user.openshift.io/groups/odh-users
  - ../../../base/user.openshift.io/groups/osc-admins
  - ../../../base/user.openshift.io/groups/grafana-viewer
  - ../../../base/user.openshift.io/groups/kubeflow-admin
  - ../../../base/user.openshift.io/groups/openshift-operators-admin 
  - ../../../base/user.openshift.io/groups/pachyderm-admins
  - ../../../base/user.openshift.io/groups/inception-admins
  - ../../../base/user.openshift.io/groups/multinode-demo
  - ../../../base/user.openshift.io/groups/openshift-operators-view
  - ../../../base/user.openshift.io/groups/seldon-admin
  - ../../../base/user.openshift.io/groups/grafana-admin
  - ../../../base/user.openshift.io/groups/kafka-admins
  - ../../../base/user.openshift.io/groups/odh-admin
  - ../../../base/user.openshift.io/groups/osc
  - ../../../base/user.openshift.io/groups/sostrades
